const fs = require('fs')
let c = fs.readFileSync('src/App.jsx', 'utf8')
c = c.replace("setErro('Erro ao enviar e-mail. Verifique o endere\u00e7o.')", "error.status === 429 ? setErro('Muitas tentativas. Aguarde 1 minuto.') : setErro('Erro ao enviar e-mail. Verifique o endere\u00e7o.')")
fs.writeFileSync('src/App.jsx', c, 'utf8')
console.log('ok:', c.includes('429'))